### ISSUE TITLE
Incompatible with EPiServer 11

### ISSUE THREAD

**Issue by jmyrland** [Romanets/RestImageResize#11]
Hi,

First off: thanks for this repo! Amazing job :clap:

Now, I just upgraded EPiServer to version 11.2.1, and I got this error message:

```
Could not load type 'EPiServer.Web.Routing.UrlResolver' from assembly 'EPiServer, Version=11.2.1.0, Culture=neutral, PublicKeyToken=8fe83dea738b45b7'.

Trigger:
OpenWaves.ServiceLocator.SetResolver(new OpenWaves.BasicResolver().RegisterRestImageResize());
```

Is there another way to register the module for episerver 11 ?

Tested version:
```
  <package id="RestImageResize" version="1.1.7" targetFramework="net461" />
  <package id="RestImageResize.EPiServer" version="1.1.1" targetFramework="net461" />
```

**Comment by VladimirLevchuk** [comment]
Hi @jmyrland. Unfortunately there is no other way of using it. We'll have to rebuild it with new episerver libraries to make it episerver 11 compatible (because of breaking changes there).

**Comment by VladimirLevchuk** [comment]
... and it requires OpenWaves upgrade, so not this year :(

**Comment by jmyrland** [comment]
Thanks for the reply. I assumed there were some breaking changes, but I was hoping for a quick fix.

I'm guessing most of the work is in upgrading the openwaves dependency, so I'm guessing we would have to wait for it to be finished.

Do you know if the openwaves source is available/open somewhere?

**Comment by VladimirLevchuk** [comment]
The only place I know is https://openwaves.codeplex.com/ (and unfortunately it's not supported any more, so it's in my task list to move it to git) 
In general the future plan is to throw OpenWaves away, add an abstraction and use https://github.com/JimBobSquarePants/ImageProcessor or https://github.com/ImageMagick/ImageMagick instead (via plugins system)

**Comment by Romanets** [comment]
Hi @jmyrland, we have updated the package, use v 2.0.0 with EPiServer 11.
